### ISSUE TITLE
Env vars for jwks_url in id_token mutator not working in versions >v0.19.0-beta.1

### ISSUE THREAD

**Issue by kubadz** [ory/oathkeeper#276] opened 2019-10-16 09:51 UTC
**Describe the bug**

Mutator `id_token` requires `jwks_url` to be configured either in global or in per-rule configuration. The global configuration in most cases can be set by env variables. As the version v0.19.0 introduced changes in config (https://github.com/ory/oathkeeper/pull/258) it is logical that also env variables might have been changed.

Previously our configuration was setting `MUTATORS_ID_TOKEN_JWKS_URL` and it obviously didn't work in the recent oathkeeper version. I set it to `MUTATORS_ID_TOKEN_CONFIG_JWKS_URL` as it is currently configured [on master](https://github.com/ory/oathkeeper/blob/fc85ac854c3fb4cdd96bbae650f7355400431eac/driver/configuration/provider_viper.go#L62) but it also didn't work.

For both cases Oathkeeper returns error
```
{"error":{"code":500,"status":"Internal Server Error","request":"7da5f8a3-8db8-45dd-b358-e7eec13cdaaa","reason":"Configuration for mutator \"id_token\" could not be validated: jwks_url is required","message":"mutator matching this route is misconfigured or disabled"}}
```
when calling a service.

**some thoughts on this issue**: I suspect that it might be related to the way how config for mutators is validated. Maybe the validation with json schema happens on the config object without jwks_url set to value from env variable. I haven't checked it thoroughly in the code, though.

**Reproducing the bug**

1. Run Oathkeeper with env var `MUTATORS_ID_TOKEN_CONFIG_JWKS_URL` set to the jwks location, and with id_token mutator in global config set as following:
```
...
      id_token:
        config:
          issuer_url: https://example.com/
          ttl: 60s
...
```
2. Create a rule for some service with mutators configured as following:
```
        "mutators": [
          {
            "handler": "id_token",
            "config": {
              "issuer_url": "https://example.com/v2"
            }
          }
        ]
```
3. Create a request to that service. The response should contain an error mentioned in the description.

_Server logs_

```
time="2019-10-16T09:43:59Z" level=info msg="started handling request" method=GET remote="127.0.0.1:38458" request=/ request_id=98490e37-3176-4905-a407-83a24781921a
time="2019-10-16T09:43:59Z" level=warning msg="Invalid mutator requested" access_url="http://lambda-default.35.187.58.27.xip.io/" authorization_handler=id_token error="mutator matching this route is misconfigured or disabled" granted=false reason_id=invalid_mutation_handler
time="2019-10-16T09:43:59Z" level=warning msg="Access request denied" access_url="http://lambda-default.35.187.58.27.xip.io/" error="mutator matching this route is misconfigured or disabled" granted=false
time="2019-10-16T09:43:59Z" level=error msg="An error occurred while handling a request" code=500 debug= details="map[]" error="mutator matching this route is misconfigured or disabled" reason="Configuration for mutator \"id_token\" could not be validated: jwks_url is required" request-id=98490e37-3176-4905-a407-83a24781921a status=500 trace="Stack trace: \ngithub.com/ory/oathkeeper/driver/configuration.(*ViperProvider).PipelineConfig\n\t/go/src/github.com/ory/oathkeeper/driver/configuration/provider_viper.go:257\ngithub.com/ory/oathkeeper/driver/configuration.(*ViperProvider).MutatorConfig\n\t/go/src/github.com/ory/oathkeeper/driver/configuration/provider_viper.go:284\ngithub.com/ory/oathkeeper/pipeline/mutate.(*MutatorIDToken).Config\n\t/go/src/github.com/ory/oathkeeper/pipeline/mutate/mutator_id_token.go:150\ngithub.com/ory/oathkeeper/pipeline/mutate.(*MutatorIDToken).Validate\n\t/go/src/github.com/ory/oathkeeper/pipeline/mutate/mutator_id_token.go:144\ngithub.com/ory/oathkeeper/proxy.(*RequestHandler).HandleRequest\n\t/go/src/github.com/ory/oathkeeper/proxy/request_handler.go:181\ngithub.com/ory/oathkeeper/proxy.(*Proxy).Director\n\t/go/src/github.com/ory/oathkeeper/proxy/proxy.go:116\nnet/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/go/src/net/http/httputil/reverseproxy.go:216\ngithub.com/urfave/negroni.Wrap.func1\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46\ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/meatballhat/negroni-logrus.(*Middleware).ServeHTTP\n\t/go/pkg/mod/github.com/meatballhat/negroni-logrus@v0.0.0-20170801195057-31067281800f/middleware.go:136\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/x/metricsx.(*Service).ServeHTTP\n\t/go/pkg/mod/github.com/ory/x@v0.0.76/metricsx/middleware.go:261\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/urfave/negroni.(*Negroni).ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337" writer=JSON
time="2019-10-16T09:43:59Z" level=info msg="completed handling request" measure#oathkeeper-proxy.latency=14988034 method=GET remote="127.0.0.1:38458" request=/ request_id=98490e37-3176-4905-a407-83a24781921a status=500 text_status="Internal Server Error" took=14.988034ms
```

**Expected behavior**

I expect the request to pass.

**Environment**

- Version: >v0.19.0-beta.1
- Environment: Docker, k8s

**Additional context**

**Comment by aeneasr** [comment] 2019-10-17 08:16
This is probably a dupe of #270 right?

**Comment by kubadz** [comment] 2019-10-17 11:06
I wouldn't say that it is a duplicate for two reasons:
* as @GuillaumeSmaha notes, the lines for env vars related to Oauth2TokenIntrospection authenticator config was removed: [link](https://github.com/ory/oathkeeper/commit/89709aabfe002fc5ae2e76016fc45a13d74f3d8b#diff-2449a6ea083767b149400840c05f41bdL58-L59) 
whether a line for specifying JWKS_URL for id_token mutator was preserved: [link](https://github.com/ory/oathkeeper/blob/fc85ac854c3fb4cdd96bbae650f7355400431eac/driver/configuration/provider_viper.go#L62)
* as I wrote in the description of this issue, I would expect that previous configuration `MUTATORS_ID_TOKEN_JWKS_URL`  would be changed to `MUTATORS_ID_TOKEN_CONFIG_JWKS_URL`, as the configuration was changed.  @GuillaumeSmaha mentions that `AUTHENTICATORS_OAUTH2_INTROSPECTION_PRE_AUTHORIZATION_CLIENT_ID` doesn't work. 
According to [this line](https://github.com/ory/oathkeeper/blob/fc85ac854c3fb4cdd96bbae650f7355400431eac/driver/configuration/provider_viper.go#L219) I would expect that the env var should look like `AUTHENTICATORS_OAUTH2_INTROSPECTION_CONFIG_PRE_AUTHORIZATION_CLIENT_ID`. Although I haven't actually tried that.

**Comment by aeneasr** [comment] 2019-10-17 13:08
While the symptoms are the different, the cause is the same, right? I think if we just add the new keys there this should be resolved right away. We should also document this in the upgrade guide then. Would you be up for that?

**Comment by aeneasr** [comment] 2019-10-21 13:51
I believe I have found the issue, [BindEnv](https://github.com/ory/oathkeeper/blob/bc67cc18b4e32331f86bc8b10f1947a812be6b7e/driver/configuration/provider_viper.go#L89) is not actually being called, causing viper to not observe those keys, hence, when trying to get the whole config, this fails.

**Comment by aeneasr** [comment] 2019-10-21 13:52
I will try to come up with a PR this week (however, we have an internal deadline for another project) and also a test to make sure this doesn't regress in the future.

**Closed** 2019-10-27 18:38 UTC
