### ISSUE TITLE
Working with query parameters

### ISSUE THREAD

**Issue by sash2222** [ory/oathkeeper#843] opened 2021-10-01 13:17 UTC
** Is your feature request related to a problem? Please describe. **

We use the so called Centrifugo subscription server. It can authenticate socket or SSE subscription requests to a proxy such as this one. But it makes requests with a list of channels to subscribe only in parameters, not in path.

** Describe the solution you'd like **

So that the outkeeper accepts channel parameters from the request and can use them in the request to the authorizer.
For example, a GET request came / path / parameters (chanel1, chanel2). The outkeeper mutates such a request (if required) and you can or cannot contact the authorizer using the parameter values ​​to obtain approval.

** Describe alternatives you've considered **

Define channels in the form of paths on the outkeeper, mutate them if the request passed the check, make the request further through the hydrator.

**Comment by aeneasr** [comment] 2021-10-03 10:36
Thank you, could you give some example API requests and flows you have? I have a bit of a hard time following because I don’t know Centrifugo

**Comment by semichkin** [comment] 2021-10-03 16:48
api example.

We have next config structure:
match:
    url: http://subs.service.dev/subscribe?<.*>subs=[<.*>]<.*>

authorizer:
    handler: remote_json
    payload: {channels: "{{ .RegexpCaptureGroups 1 }}"}


And for request: 
http://subscribes.service/subsribe?subs=[channel1, channel2, channel3]

Authorizer gets object: {channels: "channel1, channel2, channel3"}

**Comment by vinckr** [comment] 2022-09-21 15:52
Would the workaround described here solve/close this issue? 
https://github.com/ory/oathkeeper/issues/964#issuecomment-1251886904

**Comment by aeneasr** [comment] 2022-12-06 16:56
Closing this as a dupe of #964

**Closed by aeneasr** 2022-12-06 16:56 UTC
