### ISSUE TITLE
Oathkeeper bombards Ory Network with requests after upgrade to 40.x

### ISSUE THREAD

**Issue by Withel** [ory/oathkeeper#1161] opened 2024-04-25 08:23 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Ory Network Project

https://vibrant-dubinsky-6d1qtx5k0i.projects.oryapis.com

### Describe the bug

After upgrading from 39.4 to 40.7, @tricky42 notified us, about huge amount of requests made from oathkeeper to ory network's /introspect endpoint, as can be seen on the first screenshot (Upgrade was performed on 23.04 at ~15:58). From our perspective we don't see any issues in the logs or metrics. On the second screenshot you can see oathkeeper traffic (spike is from the moment of upgrade). We didn't change any configuration between the versions (except the naming of log level), and we suspect that the cache might not be working properly. 

Screenshot 1:
![image](https://github.com/ory/oathkeeper/assets/32665405/1a1fcce0-33e6-4975-847c-bf9795771301)

Screenshot 2:
![image](https://github.com/ory/oathkeeper/assets/32665405/b7d5f1b0-b840-450f-866c-65b0662f3c56)

### Reproducing the bug

1. Upgrade oathkeeper to 40.7 from 39.x 

### Relevant configuration

```yml
authenticators:
    oauth2_introspection:
      config:
        cache:
          enabled: true
          max_cost: 100
          ttl: 1h
        introspection_request_headers:
          Authorization: [REDACTED]
        introspection_url: https://[REDACTED]/admin/oauth2/introspect
        retry:
          give_up_after: 3s
          max_delay: 500ms
        token_from:
          header: Authorization
      enabled: true
```

### Version

40.7

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

Kubernetes with Helm

**Comment by aeneasr** [comment] 2024-04-25 08:24
Thank you for the report! Can you pin-point which version introduced this regression? It would make the search for the regression much easier!

**Comment by Withel** [comment] 2024-04-25 08:28
I'm not sure if I understand you correctly, as I wrote in the description, we have upgraded from 39.4 to 40.7 or do you mean something else?

**Comment by marcinfigiel** [comment] 2024-04-25 10:02
> Since there are a couple of versions between 39.4 and 40.6 I wanted to know if you specifically can pin point which version exactly introduced the issue, making it easier to find the root cause

Unfortunately not, we've only tried these two versions :(

**Comment by Withel** [comment] 2024-05-08 13:08
@aeneasr we've managed to pin-point exact version which introduces this issue. This happens between v0.39.4 and v0.40.0. Hope this helps, please let me know if you need anything else.

**Comment by aeneasr** [comment] 2024-05-09 10:35
I think your `max_cost` is just way too low. I see that we also use a misleading configuration in ristretto. The default `max_cost` is set to 100000000 which I think is way too high.

Try playing around with that value to see if it has an impact.

**Comment by aeneasr** [comment] 2024-05-09 10:43
Fix for some of the config values: https://github.com/ory/oathkeeper/commit/23730570e0ac35bec214f78a0e951501f58c598b

**Comment by aeneasr** [comment] 2024-05-09 11:02
Basically before we were using the internal cost which is I think the key length + cost function. Since your maxcost is like 100 the cache probably ran out of space after one or two keys so it's constantly evicting your values.

The fixes ignore the internal cost so you actually get 1 cost = 1 token instead of 1 token = 1 cost + cost of key

**Comment by Withel** [comment] 2024-05-09 14:15
Soooo, with the help of @Demonsthere, we checked following values of the `max_cost` value:
```
~15:05 CET: 100M (default) -> 300-400 req/m with initial spike 
~15:35 CET: 50M -> 300-400 req/m
~15:55 CET: 5M -> for a second dropped to ~270 req/m, then increased to ~300-400 req/m
```

And here's the graph:
![image](https://github.com/ory/oathkeeper/assets/32665405/d430a65d-1dec-4fa5-b1a0-0335f20ec89d)

I hope this helps, for the time being we will go back to the 39.4 and we'll wait for the further updates. Please let us know if you need anything else.

**Comment by aeneasr** [comment] 2024-05-09 15:15
So what you're saying is that it doesn't have an effect?

**Comment by Withel** [comment] 2024-05-10 08:29
So, I must admitt that I made a mistake that I realised just after posting last comment. Unfortunately, I didnt keep an eye on the pods after deployment and turned out that they were not restarting after changing `max_count`. From what I know oathkeeper does not have configuration hot reload, thus I will have to redo those experiments. Nevertheless I’m not sure when I’ll be able to perform those experiments since right now Im out of the office, but Ill do this as soon as possible. Apologies for that.

**Comment by aeneasr** [comment] 2024-05-10 08:35
Hot reloading only works for things that can be changed during runtime. Caches unfortunately are large memory objects that are allocated at process start and can not be changed at runtime.

**Comment by Withel** [comment] 2024-05-14 14:19
So, I have redo the tests (now making sure that after each update, pods are restarted correctly) and here are the results. Values same as before:
```
Before - 39.4 with max_count set to 100
9:30 CET - 40.7 with max_count set to 100 
~9:55 CET - 40.7 with max_count removed (set to 100M, default)
~10:20 CET - 40.7 with max_count set to 50M
~10:50 CET - 40.7 with max_count set to 5M
```
Results (thanks to @tricky42 curtesy): 
![image](https://github.com/ory/oathkeeper/assets/32665405/0172e09e-a5fc-4770-9066-09d9bb212abd)

Also, we were suspecting that maybe oathkeeper containers are running out of memory, but we confirmed that it's not the case:
![image](https://github.com/ory/oathkeeper/assets/32665405/5b972f1e-d7c9-4e71-a713-b6932f39dd83)

**Comment by aeneasr** [comment] 2024-05-24 10:17
OK so increasing the cache size fixes the problem?

**Comment by aeneasr** [comment] 2024-12-25 14:58
Closing this as it was a cache config issue

**Closed by aeneasr** 2024-12-25 14:58 UTC
Labels: bug
