### ISSUE TITLE
Fatal error: concurrent map writes

### ISSUE THREAD

**Issue by springjazzy** [ory/oathkeeper#906] opened 2022-02-03 13:53 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/oathkeeper/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/oathkeeper/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Oathkeeper crashed with the message "fatal error: concurrent map writes". Crush happens after enabling cache on introspection endpoint. 

### Reproducing the bug

Reproduced in our docker swarm env. 

### Relevant log output

```shell
fatal error: concurrent map writes,
goroutine 622 [running]:,
runtime.throw(0x1664730, 0x15),
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc001abc330 sp=0xc001abc300 pc=0x438652,
runtime.mapassign_faststr(0x1450940, 0xc000603050, 0x1652fba, 0x8, 0x57),
	/usr/local/go/src/runtime/map_faststr.go:291 +0x3d8 fp=0xc001abc398 sp=0xc001abc330 pc=0x414858,
github.com/ory/oathkeeper/pipeline/authn.(*AuthenticatorOAuth2Introspection).Authenticate(0xc000d831d0, 0xc0011b7500, 0xc000405d40, 0x0, 0x0, 0x0, 0x18affb0, 0xc0014b0460, 0x0, 0x0),
	/home/ory/pipeline/authn/authenticator_oauth2_introspection.go:253 +0x51e fp=0xc001abc7b0 sp=0xc001abc398 pc=0x12685fe,
github.com/ory/oathkeeper/proxy.(*RequestHandler).HandleRequest(0xc0003f5d80, 0xc0011b7500, 0xc0014b0460, 0x16c7b08, 0x14f3320, 0xc0014b0460),
	/home/ory/proxy/request_handler.go:216 +0x523 fp=0xc001abcbf0 sp=0xc001abc7b0 pc=0x12d8b43,
github.com/ory/oathkeeper/proxy.(*Proxy).Director(0xc000e14000, 0xc0011b7500),
	/home/ory/proxy/proxy.go:134 +0x596 fp=0xc001abd330 sp=0xc001abcbf0 pc=0x12d54b6,
github.com/ory/oathkeeper/proxy.(*Proxy).Director-fm(0xc0011b7500),
	/home/ory/proxy/proxy.go:125 +0x3d fp=0xc001abd350 sp=0xc001abd330 pc=0x12e73fd,
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc000e16000, 0x7f187ba77f18, 0xc001820020, 0xc0011b7000),
	/usr/local/go/src/net/http/httputil/reverseproxy.go:241 +0x16d fp=0xc001abd5b8 sp=0xc001abd350 pc=0xa2e48d,
github.com/urfave/negroni.Wrap.func1(0x7f187ba77f18, 0xc001820020, 0xc0011b7000, 0xc000d92400),
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46 +0x4d fp=0xc001abd5e8 sp=0xc001abd5b8 pc=0xbd71ed,
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc000e200a8, 0x7f187ba77f18, 0xc001820020, 0xc0011b7000, 0xc000d92400),
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29 +0x4e fp=0xc001abd618 sp=0xc001abd5e8 pc=0xbd5c2e,
github.com/urfave/negroni.middleware.ServeHTTP(0x18a53e0, 0xc000e200a8, 0xc000e20108, 0x7f187ba77f18, 0xc001820020, 0xc0011b7000),
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c fp=0xc001abd650 sp=0xc001abd618 pc=0xbd5cdc,
github.com/urfave/negroni.middleware.ServeHTTP-fm(0x7f187ba77f18, 0xc001820020, 0xc0011b7000),
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:37 +0x65 fp=0xc001abd690 sp=0xc001abd650 pc=0xbd7465,
github.com/ory/x/reqlog.(*Middleware).ServeHTTP(0xc000308000, 0x7f187ba77f18, 0xc001820020, 0xc0011b7000, 0xc000d923a0),
	/go/pkg/mod/github.com/ory/x@v0.0.163-1/reqlog/middleware.go:134 +0x2c9 fp=0xc001abd758 sp=0xc001abd690 pc=0xbfba29,
github.com/urfave/negroni.middleware.ServeHTTP(0x18a1a40, 0xc000308000, 0xc000e200f0, 0x7f187ba77f18, 0xc001820020, 0xc0011b7000),
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c fp=0xc001abd790 sp=0xc001abd758 pc=0xbd5cdc,
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:37 +0x65 fp=0xc001abd7d0 sp=0xc001abd790 pc=0xbd7465,
github.com/ory/oathkeeper/metrics.(*Middleware).ServeHTTP(0xc000e16050, 0x7f187ba77f18, 0xc001820020, 0xc0011b7000, 0xc000d92380),
	/home/ory/metrics/middleware.go:88 +0x9d fp=0xc001abd868 sp=0xc001abd7d0 pc=0x12e22dd,
github.com/urfave/negroni.middleware.ServeHTTP(0x18a18e0, 0xc000e16050, 0xc000e200d8, 0x7f187ba77f18, 0xc001820020, 0xc0011b7000),
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c fp=0xc001abd8a0 sp=0xc001abd868 pc=0xbd5cdc,
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:37 +0x65 fp=0xc001abd8e0 sp=0xc001abd8a0 pc=0xbd7465,
github.com/ory/x/metricsx.(*Service).ServeHTTP(0xc000c8ed20, 0x7f187ba77f18, 0xc001820020, 0xc0011b7000, 0xc000d92360),
	/go/pkg/mod/github.com/ory/x@v0.0.163-1/metricsx/middleware.go:261 +0x94 fp=0xc001abdad8 sp=0xc001abd8e0 pc=0xbfa334,
github.com/urfave/negroni.middleware.ServeHTTP(0x18a1a00, 0xc000c8ed20, 0xc000e200c0, 0x7f187ba77f18, 0xc001820020, 0xc0011b7000),
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c fp=0xc001abdb10 sp=0xc001abdad8 pc=0xbd5cdc,
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc0003b5620, 0x18bc6e0, 0xc0014b02a0, 0xc0011b7000),
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96 +0xf1 fp=0xc001abdb70 sp=0xc001abdb10 pc=0xbd60b1,
net/http.serverHandler.ServeHTTP(0xc0010ac0e0, 0x18bc6e0, 0xc0014b02a0, 0xc0011b7000),
	/usr/local/go/src/net/http/server.go:2887 +0xa3 fp=0xc001abdba0 sp=0xc001abdb70 pc=0x705963,
net/http.(*conn).serve(0xc000e94460, 0x18c2470, 0xc000a7f440),
	/usr/local/go/src/net/http/server.go:1952 +0x8cd fp=0xc001abdfc8 sp=0xc001abdba0 pc=0x700e8d,
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc001abdfd0 sp=0xc001abdfc8 pc=0x4723a1,
runtime.goexit(),
created by net/http.(*Server).Serve,
	/usr/local/go/src/net/http/server.go:3013 +0x39b,
goroutine 1 [semacquire, 2 minutes]:,
sync.runtime_Semacquire(0xc0004d0008)
...
```

### Relevant configuration

```yml
authenticators:
  noop:
    enabled: true

  oauth2_introspection:
    enabled: true
    config:
      introspection_url: https://idp-hydra:4445/oauth2/introspect
      scope_strategy: exact
      retry:
        max_delay: 300ms
        give_up_after: 2s
      cache:
        enabled: true
```

### Version

0.38.15

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker

### Additional Context

We are struggling to pass through load test of our system and current bottleneck is oauthkeeper with hydra. We have load test written in [k6](https://k6.io/docs/) with 4 500 virtual users. With oauthkeeper 0.37 we've seen numerous 
`context deadline exceeded (Client.Timeout exceeded while awaiting headers)` 500 errors from introspection endpoint. The idea was to cache tokens to minimize request numbers to introspection.

**Comment by aeneasr** [comment] 2022-04-11 20:23
I looked into this but I'm not quite sure what the problem is. Do you experience this problem with [v0.38.24-beta.1](https://github.com/ory/oathkeeper/releases/tag/v0.38.24-beta.1) also and if so, could you please probide an update stack trace?

**Comment by aeneasr** [comment] 2022-04-28 15:10
Thank you for the follow up! Closing :)

**Closed by aeneasr** 2022-04-28 15:10 UTC
Labels: bug
